services:
  ws:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    configs:
      - source: smnrp
        target: /run/configs/smnrp.yml
    env_file: .env
  echo:
    platform: linux/amd64
    image: kennethreitz/httpbin
    environment:
      TZ: "Europe/Zurich"
configs:
  smnrp:
    file: ./smnrp.yml
