volumes:
  smnrp_data:
services:
  ws:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - smnrp_data:/etc/letsencrypt
    configs:
      - source: smnrp
        target: /run/configs/smnrp.yml
  echo:
    platform: linux/amd64
    image: kennethreitz/httpbin
    environment:
      TZ: "Europe/Zurich"
configs:
  smnrp:
    file: ./smnrp.yml
  #   depends_on:
  #     - mail
  # mail:
  #   image: axllent/mailpit:v1.27.5
  #   hostname: mail
  #   restart: unless-stopped
  #   ports:
  #     - 8025:8025
